name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *"  # Executa todos os dias à meia-noite (UTC)
  workflow_dispatch:     # Permite execução manual pelo GitHub

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: FerSouzza
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
